[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix frontend --legacy-peer-deps",
  "npm install --prefix backend --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "cp -r frontend/dist backend/public"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && node src/server.js"
